version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    ignore:
      - dependency-type: development
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Upgrade(npm):"
      prefix-development: "Upgrade(dev):"
    reviewers:
      - "evelynhathaway"
    assignees:
      - "evelynhathaway"
